# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true
gems:                [jekyll-paginate]

# Setup
title:               'RaEmber''s Homepage'
url:                 'http://raember.github.com/'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Raphael Emberger
  url:               'https://github.com/RaEmber'
  email:             raphael.emberger@hotmail.ch

# Custom vars
version:             1.0.0
